### ISSUE TITLE
How To Use?

### ISSUE THREAD

**Issue by D86** [JacquesDiringer/Procedural_hardsurface#1]
How do I use this? I've installed it to my add on's folder but its not showing up in the search bar?

**Comment by JacquesDiringer** [comment]
Yeah the script is really primitive for now, you will have to run it manually:
- Open the scripting layout of Blender
- In the text editor window: "Text"->"Open", then select the script corresponding to your Blender version
- Finally, click "Run Script" -> new meshes will be added in the 3D view

I will add this to the Readme of the git project
